
name: CD

on:
  push:
    branches: [ master ]

jobs:
  generate-strategy-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: dschep/install-pipenv-action@v1
    - run: pipenv install
    - id: set-matrix
      run: |
        OUTPUT=$(pipenv run python generate_strategy_matrix.py --owner pypa --name pipenv --last_n 5 --token ${{ secrets.TOKEN }})
        echo "::set-output name=matrix::$OUTPUT"
  build-all-images:
    needs: generate-strategy-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-strategy-matrix.outputs.matrix)}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: create Dockerfile from template
      run: |
        envsubst < Dockerfile.template > Dockerfile
      env:
        PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
        PIPENV_VERSION: ${{ matrix.PIPENV_VERSION }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tolgaeren/pipenv-in-a-container
        tags: ${{ matrix.tags }}
  